FROM node:16-bullseye-slim

# Load all the environment variables
ARG ENV_VARIABLES

ARG BUILD_ID
ENV BUILD_ID=$BUILD_ID

LABEL stage=Stage1
LABEL build=$BUILD_ID

ENV NODE_ENV=production \
    PROJECT_HOME=/usr/app/ \
    DEBUG="app:*" \
    BUILD_DEPS="git python openssh-server build-essential"


# More node size for the docker build
ENV NODE_OPTIONS=--max_old_space_size=5120

# create project home
RUN mkdir -p ${PROJECT_HOME}

# switch to working directory
WORKDIR ${PROJECT_HOME}

# Copy the ssh folder to the home directory
COPY ./.ssh /root/.ssh/

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ${PROJECT_HOME}

# install deps
RUN apt-get update > /dev/null \
    && apt-get install -y -qq --no-install-recommends ${BUILD_DEPS} ca-certificates \
    vim curl > /dev/null

#npm install
RUN npm i -g npm \
    && npm install --quiet

# copy source code and run the build
COPY . $PROJECT_HOME

# Exporting to the environment before build rather than using .env file
RUN IFS=';'; \
    for item in $ENV_VARIABLES; do \
#    echo $item; \
    export $item; \
    done \
    && npm run build

#cleanup
RUN apt-get purge -y ${BUILD_DEPS} > /dev/null \
    && rm -rf /var/lib/apt/lists/*


EXPOSE 80 443 8080

# start the application
CMD ["npm","start"]